const BOOKMARK_FEED = "BOOKMARK_FEED";
const UNBOOKMARK_FEED = "UNBOOKMARK_FEED";

const FETCH_FEED = "FETCH_FEED";
const ADD_FEED_URL = "ADD_FEED_URL";
const REMOVE_FEED_URL = "REMOVE_FEED_URL";

const ADD_LOCAL_FEED = "ADD_LOCAL_FEED";
const REMOVE_LOCAL_FEED = "REMOVE_LOCAL_FEED";

export {
  BOOKMARK_FEED,
  UNBOOKMARK_FEED,
  FETCH_FEED,
  ADD_FEED_URL,
  REMOVE_FEED_URL,
  ADD_LOCAL_FEED,
  REMOVE_LOCAL_FEED,
};
